name: Github actions docker image build and publish

on:
  push:
    tags:
      -v*.*.*

jobs:
  build_and_publish:
    name: Build and publish the docker image
    runs-on: ubuntu-latest
    run: |
      echo env
      docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
      docker build -t $DOCKER_USERNAME/github-actions-docker:latest .
      docker push DOCKER_USERNAME/github-actions-docker:latest
