name: Github actions docker image build and publish

on:
  push:
    branches:
      - master
#    tags:
#      - v*.*.*

jobs:
  build_and_publish:
    name: Build and publish the docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          env
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions-docker:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/github-actions-docker:latest
